def sqrt_n_times(x,n):
    a=float(x)
    b=float(n)
    c=x**(0.5**n)
    return c
def cube_root(y):
    a=float(y)
    b=sqrt_n_times(a,2)
    c=sqrt_n_times(a,4)
    d=sqrt_n_times(a,6)
    e=sqrt_n_times(a,8)
    f=sqrt_n_times(a,10)
    g=sqrt_n_times(a,12)
    h=sqrt_n_times(a,14)
    i=sqrt_n_times(a,16)
    j=sqrt_n_times(a,18)
    k=sqrt_n_times(a,20)
    l=sqrt_n_times(a,22)
    m=sqrt_n_times(a,24)
    n=sqrt_n_times(a,26)
    o=sqrt_n_times(a,28)
    p=sqrt_n_times(a,30)
    q=sqrt_n_times(a,32)
    r=sqrt_n_times(a,34)
    s=sqrt_n_times(a,36)
    t=sqrt_n_times(a,38)
    u=sqrt_n_times(a,40)
    v=sqrt_n_times(a,42)
    w=sqrt_n_times(a,44)
    x=sqrt_n_times(a,46)
    y=sqrt_n_times(a,48)
    z=sqrt_n_times(a,50)
    aa=sqrt_n_times(a,52)
    bb=sqrt_n_times(a,54)
    cc=sqrt_n_times(a,56)
    dd=sqrt_n_times(a,58)
    ee=sqrt_n_times(a,60)
    ff=sqrt_n_times(a,62)
    gg=sqrt_n_times(a,64)
    return b*c*d*e*f*g*h*i*j*k*l*m*n*o*p*q*r*s*t*u*v*w*x*y*z*aa*bb*cc*dd*ee*ff*gg
def main():
    q = float(input())
    print(cube_root(q))
exec(input())